# syntax=docker/dockerfile:1

FROM rust:1.84-slim-bookworm AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
    cmake \
    libclang-dev \
    protobuf-compiler \
    build-essential \
    git \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add wasm32-unknown-unknown

WORKDIR /opt/qf-solochain

COPY . .

# Build the node
# --locked ensures strictly reproducible builds based on Cargo.lock
RUN cargo build --release --locked --bin qf-node --bin qf-parachain-node

FROM debian:bookworm-slim AS runtime

ARG QF_REF

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    # Added for debugging:
    net-tools iputils-ping nano less dnsutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/qf-solochain

COPY --from=builder /opt/qf-solochain/target/release/qf-node /usr/local/bin/qf-node
COPY --from=builder /opt/qf-solochain/target/release/qf-parachain-node /usr/local/bin/qf-parachain-node

LABEL org.opencontainers.image.authors="QF Network <admin@qfnetwork.xyz>"
LABEL org.opencontainers.image.source="https://github.com/QuantumFusion-network/qf-solochain"
LABEL org.opencontainers.image.revision="${QF_REF}"

# No ENTRYPOINT or CMD - will be provided by docker-compose
