[relaychain]
default_command = "./target/release/qf-node"
chain_spec_path = "./node/src/res/qf-local.raw.json"
args = ["--state-pruning archive"]

[[relaychain.nodes]]
name = "alice"
balance = 1000000000000000000000000
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
balance = 1000000000000000000000000

[[relaychain.nodes]]
name = "charlie"
balance = 1000000000000000000000000

[[relaychain.nodes]]
name = "dave"
validator = false
balance = 1000000000000000000000000

[[relaychain.nodes]]
name = "eve"
validator = false
balance = 1000000000000000000000000
