[relaychain]
default_command = "~/.cargo/target/release/qf-node"
chain = "local"
args = ["--state-pruning archive --blocks-pruning archive"]

[[relaychain.nodes]]
name = "alice"

[[relaychain.nodes]]
name = "bob"

[[relaychain.nodes]]
name = "charlie"

[[relaychain.nodes]]
name = "dave"
validator = false

[[relaychain.nodes]]
name = "eve"
validator = false
