name: Build

on:
  push:
    branches:
      - runner-test

jobs:
  build_binary:
    name: Build Binary
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y gcc g++ make curl git protobuf-compiler libclang-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add wasm32-unknown-unknown --toolchain nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build Project
        run: |
          cargo --version
          make vendor-clone
          make qf-node

      - name: Generate checksums
        run: |
          shasum -a 256 output/qf-node > output/qf-node.sha256
